version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trader
      POSTGRES_DB: trading
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  trading_engine:
    build:
      context: .
      dockerfile: services/trading_engine/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    depends_on:
      - redis

  streaming_service:
    build:
      context: .
      dockerfile: services/streaming_service/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "7000:7000"
    depends_on:
      - redis

  trading_bot:
    build:
      context: .
      dockerfile: services/trading_bot/Dockerfile
    env_file:
      - .env
    environment:
      - TEST_MODE=1
      - AUTO_TRADE=0
      - WEBAPP_HOST=0.0.0.0
    volumes:
      - ./.env:/app/.env:ro
      - ./data:/app/data
      - ./models:/app/models
    expose:
      - "8000"
    ports:
      - "8004:8000"
    depends_on:
      - redis

  analytics:
    build:
      context: .
      dockerfile: services/analytics/Dockerfile
    environment:
      - ANALYTICS_DATABASE_URL=postgresql+psycopg2://trader:trader@postgres:5432/trading
    ports:
      - "5002:5002"
    depends_on:
      - postgres

  ai_service:
    build:
      context: .
      dockerfile: services/ai_service/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5003:5003"

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    environment:
      - AI_URL=http://ai_service:5003
      - TRADING_URL=http://trading_engine:8000
      - ANALYTICS_URL=http://analytics:5002/graphql
      - BOT_SERVICE_URL=http://trading_bot:8000
    ports:
      - "8080:8080"
    depends_on:
      - trading_engine
      - ai_service
      - analytics
      - trading_bot

volumes:
  postgres_data:
